# Generated by Django 3.0.1 on 2019-12-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Username',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
