# Generated by Django 3.0.1 on 2019-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0002_userdetails_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=20)),
                ('Refno', models.PositiveIntegerField(default=1)),
                ('A_Type', models.CharField(choices=[('c', 'C'), ('s', 'S')], max_length=1)),
                ('D_Type', models.CharField(choices=[('g', 'G'), ('p', 'P'), ('u', 'U')], max_length=1)),
            ],
        ),
    ]
