# Generated by Django 3.0.1 on 2019-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0003_userinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
            ],
        ),
    ]
