# Generated by Django 3.0.1 on 2019-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0004_strarray'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrArray',
        ),
        migrations.AddField(
            model_name='userinput',
            name='result',
            field=models.TextField(default=0, max_length=50),
        ),
    ]
