# Generated by Django 3.0.1 on 2019-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0005_auto_20191229_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
