# Generated by Django 3.0.1 on 2019-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_app', '0006_userinput_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
